const { decode } = require("jsonwebtoken")

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkZyYW5jaXMiLCJsYXN0bmFtZSI6IkFMQVBISUEiLCJjb250YWN0IjoiOTE1OTU5MTQiLCJyZW5faG91c2UiOjEsImJpcnRoZGF5IjpudWxsLCJnZW5kZXJfaWQiOm51bGwsInJvbGVfaWQiOjEsImNyZWF0ZWRBdCI6IjIwMjQtMDMtMjJUMTQ6MjQ6NDEuMDAwWiIsInVwZGF0ZWRBdCI6IjIwMjQtMDMtMjJUMTU6Mjc6MDcuMDAwWiIsIkdlbmRlci5pZCI6bnVsbCwiR2VuZGVyLmxhYmVsIjpudWxsLCJHZW5kZXIuY3JlYXRlZEF0IjpudWxsLCJHZW5kZXIudXBkYXRlZEF0IjpudWxsLCJSb2xlLmlkIjoxLCJSb2xlLmxhYmVsIjoiYWRtaW4iLCJSb2xlLmNyZWF0ZWRBdCI6IjIwMjQtMDMtMjJUMTI6MTY6MDkuMDAwWiIsIlJvbGUudXBkYXRlZEF0IjpudWxsLCJpYXQiOjE3MTExMzM2MjIsImV4cCI6MTcxMTIyMDAyMn0.inK9pSl8ljwDAGIWw0giuJHIJrwFfKjbYhJkc3eqHgA"
const mpd_chiffrement = "hjshd@°#§@¦@°§°§¬¬|@°§°@§#¬§575dAj"

console.log(decode(token,mpd_chiffrement))