// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwjfJU9I8XgFvwGHaKVNb2wQ2YCg8qOI',
    appId: '1:163477761203:web:050f2eb2f689ab1d8a54c6',
    messagingSenderId: '163477761203',
    projectId: 'easyroom-17f28',
    authDomain: 'easyroom-17f28.firebaseapp.com',
    storageBucket: 'easyroom-17f28.appspot.com',
    measurementId: 'G-KDHPGXP3HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKW7ohxpxMdAhrAfun5YXuTPvUbr61FeU',
    appId: '1:163477761203:android:e8f6a7b6411116a28a54c6',
    messagingSenderId: '163477761203',
    projectId: 'easyroom-17f28',
    storageBucket: 'easyroom-17f28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwA8cGt9QBqJNWq2M7iIr443HyZ3Xn5xU',
    appId: '1:163477761203:ios:fec76c1ec0c880358a54c6',
    messagingSenderId: '163477761203',
    projectId: 'easyroom-17f28',
    storageBucket: 'easyroom-17f28.appspot.com',
    iosBundleId: 'com.example.easyroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwA8cGt9QBqJNWq2M7iIr443HyZ3Xn5xU',
    appId: '1:163477761203:ios:fec76c1ec0c880358a54c6',
    messagingSenderId: '163477761203',
    projectId: 'easyroom-17f28',
    storageBucket: 'easyroom-17f28.appspot.com',
    iosBundleId: 'com.example.easyroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkwjfJU9I8XgFvwGHaKVNb2wQ2YCg8qOI',
    appId: '1:163477761203:web:51091fc33dce050e8a54c6',
    messagingSenderId: '163477761203',
    projectId: 'easyroom-17f28',
    authDomain: 'easyroom-17f28.firebaseapp.com',
    storageBucket: 'easyroom-17f28.appspot.com',
    measurementId: 'G-X90TLK4Z0K',
  );
}
